### ISSUE TITLE
Update depot_tools for Python 3.13 compatibility

### ISSUE THREAD

**Issue by ArcticLampyrid** [rust-skia/rust-skia#1049]
Today, GH updated the macos-14-arm64 image to the version bundled with Python 3.13 for me, and then I encountered an error.

The pipes module was removed completely in Python 3.13, we may need to upgrade some code (maybe just sync with the upstream?)

https://github.com/rust-skia/depot_tools/blob/73a26246e50c0718e1b604040937bd3e1af428d4/gclient_utils.py#L19

**Comment by tronical** [comment]
This works as a fix:

```patch
diff --git a/gclient_utils.py b/gclient_utils.py
index 84d9679..88f35e4 100644
--- a/gclient_utils.py
+++ b/gclient_utils.py
@@ -16,7 +16,7 @@ import io
 import logging
 import operator
 import os
-import pipes
+import shlex
 import platform
 import re
 import stat
@@ -384,7 +384,7 @@ def safe_makedirs(tree):

 def CommandToStr(args):
   """Converts an arg list into a shell escaped string."""
-  return ' '.join(pipes.quote(arg) for arg in args)
+  return ' '.join(shlex.quote(arg) for arg in args)


 class Wrapper(object):
```

I'm not sure yet how to apply this cleanly to the build though.

**Comment by tronical** [comment]
Upstream fix: https://chromium.googlesource.com/chromium/tools/depot_tools/+/b808b1bcdd79b344246e0147e98708b91b4573fa

**Comment by tronical** [comment]
@pragmatrix what's the procedure for updating depot_tools? A PR that syncs from the main branch and then a submodule update and change to `Cargo.toml`?

**Comment by pragmatrix** [comment]
We can fix the this problem by updating to the latest depot tools and adding ninja to DEPS, but since there are no ninja binaries in the depot_tools anymore (they've been [removed a long time ago](https://groups.google.com/a/chromium.org/g/chromium-dev/c/xFYvFYGQUGI), I'd suggest to completely remove the need for depot_tools and expect ninja to be installed and available from the PATH. The builds in the repository seem to be fine (see #1051). @tronical What about slint, is it possible to make ninja available as a prerequisite similar to python3 for all the builds needed?

**Comment by tronical** [comment]
Sounds good to me. Ninja is fairly established by now. This seems to simplify the overall setup 👍👍

**Comment by RJS32** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
