### ISSUE TITLE
[Android] Cannot locate symbol 

### ISSUE THREAD

**Issue by triniwiz** [rust-skia/rust-skia#142]
Hi lovely work btw I've been monitoring this repo for a while now ...... so I'm building for android an I only get missing symbol errors if I try setting another font other than using the default values ... any help will be appreciated 
 ```java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN11SkFontStyle6NormalEv" referenced by "/data/app/com.github.triniwiz.canvasdemo-IUBq5oT_0-heYZaI1jYbLg==/lib/arm64/libcanvasnative.so"```

**Comment by pragmatrix** [comment]
Hi @triniwiz,

I've noticed is that the symbol `SkFontStyle::Normal` isn't used in any code of skia-safe, so I suspect that you are using `skia-bindings/src/bindings.rs` directly, which may cause all kinds of linker errors. `SkFontStyle::Normal()` is declared as `static constexpr` and probably expected to be compiled into the client code, which Rust won't. Because of that we have added a number of wrapper functions to `skia-bindings/src/bindings.cpp` mitigate linker errors with the primary goal to support skia-safe.

So I guess you need to use skia-safe's `FontStyle::normal()` function, or build a wrapper function on your own.

**Comment by pragmatrix** [comment]
... and if I guessed wrong, a minimal repro would help to continue here. Besides of that I'll do some further tests on Android, where I've found one testcase failing that may be related.

**Comment by triniwiz** [comment]
Oh sweet will try 🙂

**Comment by pragmatrix** [comment]
Closing this, please reopen if this continues to be an issue.
