### ISSUE TITLE
URLs in PDF are missing the last character

### ISSUE THREAD

**Issue by romanzes** [rust-skia/rust-skia#150]
I'm using the following code to add a clickable URL area to a PDF I'm rendering:
```rust
    fn add_url(&mut self, rect: &SkRect, url: &str) {
        self.canvas.draw_annotation(
            rect.to_skia(),
            "SkAnnotationKey_URL",
            &mut Data::new_copy(url.as_bytes())
        );
    }
```
However, the clickable area in the resulting PDF is missing the last character. For example, if `url` was "http://google.com", it would become "http://google.co".

**Comment by pragmatrix** [comment]
I'd assume that the last character is chopped off because the function expects `Data` to be a `CStr` including the terminating 0 byte. Try converting `url` to a `CStr` first and then use `Data::new_cstr`, something like `Data::new_cstr(&CString::new(url)))` or `Data::new_copy(CString::new(url).to_bytes_with_nul())`.

**Comment by romanzes** [comment]
Thanks @pragmatrix, your suggestion works. Would it make sense to add a method creating `Data` from `&str` though, for easier discoverability?

**Comment by pragmatrix** [comment]
@romanzes Yes, sure, but I'd rather make the need for `Data` "undiscoverable" because it is conceptually covered by `[u8]` already, and support an implicit conversions from `&str` to Data instead, like an `impl Into<Data>` and a `From<&str> for Data` trait implementation. Not sure what the consequences are, though.

**Comment by pragmatrix** [comment]
I now think it's best to go along with your suggestion by adding a function `Data::new_str()`: #151.
