### ISSUE TITLE
Publish skia-bindings to crates.io?

### ISSUE THREAD

**Issue by upsuper** [rust-skia/rust-skia#152]
It would be great if at least skia-bindings can be published to crates.io, so that other crates can start depending on the bindings as a common foundation.

For example, resvg is adding skia backend in RazrFalcon/resvg#44, but they currently use a custom binding to skia, which can cause problem when people want to combine rust-skia with resvg in the same project.

So it would be beneficial if at least the bindings can be published to crates.io.

Ideally, it would be great if Servo team can hand over the `skia-sys` crate to this project.

**Comment by pragmatrix** [comment]
Right now skia-bindings has three distinct responsibilities. First, it actually builds Skia, then it makes _most_ of the Skia API available by generating the `src/bindings.rs` file,  and finally works around limitations in LLVM and bindgen to provide functions that wouldn't be otherwise usable, that's what the `src/bindings.cpp` is for.

Because of the complexities involved taming linker errors and build problems, I never considered skia-bindings as a stable package that could be used independently, instead, it was meant to support skia-safe, which in turn I'd like to see to evolve with clearly defined rules to preserve backwards compatibily, all that while adjusting skia-bindings _as needed_ without considering dependent packages.

Said that, and considering what was discussed in resvg, I'd suggest to create a second "backend" that uses skia-safe. This way users can decide to link dynamically with Skia using the existing minimal set of bindings or statically with skia-safe / skia-bindings.

If that aligns, I'd happy to release early packages of skia-bindings and skia-safe to crates.io even though there is absolutely no documentation (yet) and also may provide help with creating the backend.

**Comment by RazrFalcon** [comment]
> I'd suggest to create a second "backend" that uses skia-safe

Supporting two backends is no go. Too much work.

To use this bindings in the resvg:

- They should be available on crates.io
- They should support older Skia versions.
- They should support prebuilt Skia.

Since Skia is very configurable and it takes a lot of time to build it, I don't think that the ability to build it via cargo is that important.

**Comment by upsuper** [comment]
> Supporting two backends is no go.

I think there are several possible approaches forward:
1. building a separate backend, or
2. having the backend support switching which bindings via a feature, or
3. making this bindings perfectly match your requirements so that the backend can switch.

I suppose both 1 and 2 require roughly the same amount of work from resvg side, so @RazrFalcon would likely be unhappy anyway. And 3 requires significant work from rust-skia side which I'm not sure how much needed, especially supporting old versions.

Given this situation, and that we don't need supporting older Skia, neither do we care about prebuilt Skia, I guess we would build and maintain our own backend at least for now, and with that, having skia-bindings on crates.io is probably no longer necessary then...

**Comment by pragmatrix** [comment]
A first set of crates were released today: [skia-safe](https://crates.io/crates/skia-safe), [skia-bindings](https://crates.io/crates/skia-bindings). 

@upsuper Glad to see your team working at the SVG backend, tell me if you need something.
