### ISSUE TITLE
Reduce release build output

### ISSUE THREAD

**Issue by triniwiz** [rust-skia/rust-skia#174]
Is there a way to reduce the out lib size for ios ? Atm I get `aarch-64 : ~28MB` , `x86_64 : 39.6MB` a bit worried since android is about 9MB and 10MB

**Comment by pragmatrix** [comment]
Hello @triniwiz !

Why are you worried? These are static lib files which contain a lot of platform dependent debug information, but their size should not matter for production use because only data and functions that are actually used should find their way into the final executable. 

If you need to reduce the size of the executables, there are several options outlined here: https://github.com/johnthagen/min-sized-rust.

For example, I tried to build the skia-org example for iOS `aarch-64` and stripped it using [`RUSTFLAGS='C link-arg=-s'`](https://github.com/rust-lang/cargo/issues/3483) and it went down from 11.2MB to 5.9 MB in size, and for Android from 12.7MB to 6.3MB, so I don't see much of a difference there.

**Comment by triniwiz** [comment]
Sorry I didn't make myself clear so the IOS builds seems large vs android but thanks for the info and link 😁

**Comment by pragmatrix** [comment]
I've never used a native Rust library from Java in Android or iOS, but it seems [that you need to build a dynamic library to link against](https://medium.com/visly/rust-on-android-19f34a2fb43), and that library must expose a C API callable from Java / Swift. So I guess that the optimizations in [the article mentioned](https://github.com/johnthagen/min-sized-rust) will also apply to a dynamic library.

Regarding the actual size difference, I have absolutely no idea where that comes from, but I consider this an implementation detail which falls in the realm of the compiler designers, and so as long it does not blow up the resulting executables or slows down the build process considerably, I don't see that as relevant for now. 

Closing this, please reopen if that stays to be a concern.
