### ISSUE TITLE
Cargo gets stuck fetching the repo occasionally 

### ISSUE THREAD

**Issue by velyan** [rust-skia/rust-skia#179]
Hey, 

I am experiencing an issue where cargo gets stuck fetching the repo. It looks like this:
```
Updating git repository `https://github.com/rust-skia/rust-skia`
warning: spurious network error (2 tries remaining): SecureTransport error: connection closed via error; class=Net (12)
```

Eventually, I would get an error saying there was an issue cloning `depot_tools`. If I manually clone `depot_tools` in `~/.cargo/git/checkouts/` I am able to get past this issue. 

It's likely related to this [cargo issue](https://github.com/rust-lang/cargo/issues/6513).

I was wondering if anyone else has seen this and if there is a better fix for it. Maybe we can add documentation with some troubleshooting steps?

**Comment by pragmatrix** [comment]
> if there is a better fix for it

If possible, I'd recommend to use a local clone for developement and refer to it [like so](https://github.com/pragmatrix/emergent/blob/779197c7e27375197af23de4635423017e38c85e/Cargo.toml#L31-L32). 

I've never seen such a problem not even on Azure. Although there were temporary errors with downloading the Skia repository probably because of its sheer size, I can not remember a single incident when the rust-skia repository could not be downloaded because of network errors, so I think this may be a problem related to the network the machine is connected to.

**Comment by velyan** [comment]
Thanks, I'll try to diagnose it better.
