### ISSUE TITLE
Linux Cross Compilation

### ISSUE THREAD

**Issue by StewartCanva** [rust-skia/rust-skia#247]
Hello,

Is there anyway to cross compile this library for linux from Mac-OS (specifically the target `x86_64-unknown-linux-gnu`)? Currently when running `cargo build --target x86_64-unknown-linux-gnu` on our project that uses this library, the `open-ssl` dependency (one of `curl`'s dependencies) fails. Looking into it, it seems like we have to also build out the `open-ssl` library manually according to https://docs.rs/crate/openssl-sys/0.9.19 . Was wondering if there's anything already set up to do this considering there's support for building for android. Our current work around is to build our project within a virtual machine or docker container, which isn't ideal.

Cheers

**Comment by pragmatrix** [comment]
Interesting, I've never tried that, but will tomorrow.

But what confuses me is that the curl dependency is used for the build only, and since the build script is executed on the host, it should not need to be compiled for the target.

**Comment by pragmatrix** [comment]
@StewartCanva I am not sure why you experience build problems with curl and openssl-sys, as said, these dependencies do not need to be compiled for the target, just for the host, which worked fine in the cross-compilation builds I tried today on Windows and macOS.

Leading up to the actual problem, which is cross-compiling Skia. 

For cross-compiling to Android, there is dedicated support in Skia's build scripts, which needs the Android NDK that comes with header files, libraries, and clang executables specific to the supported architectures. And while I think that it is possible to configure Skia for cross-compiling to other targets, I suspect that it needs a platform specific LLVM installation for each target because of the C / C++ header files, system libraries and perhaps even specific clang executables.

That said, and to answer your question: I don't see a simple way to cross-compile for any of the targets Rust is supporting except the ones the Skia build scripts support.

There is one interesting option though. If the skia-bindings crate is downloaded from crates.io, prebuilt binaries can be used to make skia-bindings and skia-safe set up target libraries for architectures other than the host. But in this case linking a binary fails for some reason.

So, while this is certainly possible with some effort, I doubt that it is worth to support in the long run. And given that you already use a working solution by using VMs or docker containers, I am closing this issue.
