### ISSUE TITLE
Compile failed when using rust-skia as git dependency

### ISSUE THREAD

**Issue by messense** [rust-skia/rust-skia#253]
```toml
skia-safe = { git = "https://github.com/messense/rust-skia.git", branch = "harfbuzz-subset", features = ["shaper"] }
```

compile failed on Linux with error message:

```
[skia-bindings 0.24.0] cargo:rerun-if-env-changed=SKIA_DEBUG
[skia-bindings 0.24.0] HOST: x86_64-unknown-linux-gnu
[skia-bindings 0.24.0] STARTING A FULL BUILD
[skia-bindings 0.24.0] You need to run this command from the toplevel of the working tree.
[skia-bindings 0.24.0] thread 'main' panicked at '`git submodule update` failed', /root/.cargo/git/checkouts/rust-skia-4eec13e24cc425ee/8c4d7de/skia-bindings/build_support/skia.rs:1041:13
[skia-bindings 0.24.0] note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
error: failed to run custom build command for `skia-bindings v0.24.0 (https://github.com/messense/rust-skia.git?branch=harfbuzz-subset#8c4d7de4)`

Caused by:
  process didn't exit successfully: `/io/target/release/build/skia-bindings-84b5ca5badade041/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-env-changed=SKIA_DEBUG
HOST: x86_64-unknown-linux-gnu
STARTING A FULL BUILD
```

The offending code is located at:

https://github.com/rust-skia/rust-skia/blob/8ec4b22da1d00ba53a2e76f9591f0f1b94541edc/skia-bindings/build_support/skia.rs#L1044-L1058

The problem is that when doing that git submodule update operation, current working directory is `/root/.cargo/git/checkouts/rust-skia-4eec13e24cc425ee/8c4d7de/skia-bindings` and it's indeed not the toplevel of the working tree.

**Comment by messense** [comment]
How about adding a new environment variable to control it?

```patch

➜  rust-skia git:(master) ✗ git --no-pager diff
diff --git a/skia-bindings/build_support/skia.rs b/skia-bindings/build_support/skia.rs
index 1f7a5d6..58bed35 100644
--- a/skia-bindings/build_support/skia.rs
+++ b/skia-bindings/build_support/skia.rs
@@ -1038,7 +1038,7 @@ mod prerequisites {
     /// submodules, or when the build.rs was called outside of the git repository,
     /// by downloading and unpacking them from GitHub.
     pub fn resolve_dependencies() {
-        if cargo::is_crate() {
+        if cargo::is_crate() || cargo::env_var("FORCE_SKIA_DOWNLOAD_DEPS").is_some() {
             // we are in a crate.
             download_dependencies();
         } else {
```

**Comment by pragmatrix** [comment]
Something is not what it seems to be. I've created a small test program with `cargo new` and the following `Cargo.toml`:

```toml
[package]
name = "skia-dep"
version = "0.1.0"
authors = ["Armin"]
edition = "2018"

[dependencies]
skia-safe = { git = "https://github.com/messense/rust-skia.git", branch = "harfbuzz-subset", features = ["shaper"] }
```

And cargo _always_ created a `.git` directory at `~/.cargo/checkouts/git/rust-skia-[hash]/[hash]/.git` and all builds went fine on Linux and Windows.

`git submodule update --init` should also be able to run within a subdirectory, as long it is running inside a workspace [since git version 1.8.4](https://stackoverflow.com/questions/21856214/git-submodule-update-why-from-toplevel).

Can you try to find out why this behaves differently on the Linux you are building on?

**Comment by messense** [comment]
```bash
#git --version
git version 1.8.3.1
```

Indeed it is caused by a very old version of `git`, it doesn't even support `git submodule update` with `--depth` argument.

**Comment by pragmatrix** [comment]
@messense I am closing this as won't fix, reopen if you want to follow up on that. 

BTW: Because I see a use case for testing the crate dependency downloads inside the repository, I've experimented with your suggestion above that introduces an environment variable to cause a direct download of the submodules. But the build failed and I wasn't sure if that would cause additional conflicts, so I'll decided to postpone this until it comes up again.
