### ISSUE TITLE
Thread-safety and Send's

### ISSUE THREAD

**Issue by ostera** [rust-skia/rust-skia#290]
Hi!

I've started to write some bindings for Erlang to Skia through this library, and I quickly hit a blocker with structs not implementing Send.

I'm not a Skia expert, but [from](https://groups.google.com/forum/#!searchin/skia-discuss/thread$20safe%7Csort:date/skia-discuss/TUy0I596FlM/dB8ul_s3CAAJ) [reading](https://groups.google.com/forum/#!topic/skia-discuss/-G1cyl1QD9E) [around](https://www.google.com/search?q=site%3Aapi.skia.org+thread+safe) I've found that many of them (with exceptions like at least `SkTypeface` and `SkBitmap`) should be safe to implement Send on under most circumstances.

Do you think it would be a good idea to do this sort of work? I'd be happy to volunteer some time onto it.

**Comment by pragmatrix** [comment]
Hello @ostera!

> Do you think it would be a good idea to do this sort of work?

Yes, of course!

Some thoughts:

- I think we can assume that all reference counted types are safe to `Send` when their reference count is 1 and do not refer to other (sharable) types. We could solve that in a similar manner like [`Rc::try_unwrap`](https://doc.rust-lang.org/std/rc/struct.Rc.html#method.try_unwrap) returning a wrapper that is `Send` and can be converted to `RCHandle<T>` in another thread. Depending on your use-case that may already solve what you need.
- An `RCHandle<T>` that is directly `Send`, must be also be `Sync`. Because the handle could be cloned and then sent to another thread pointing to the same object, effectively resulting in a handle that is `Sync`.
- All immutable and thread safe types like `SkTypeface` can be `Send + Sync` directly on their wrapper type.
- For some types, there is documentation available in the Skia sources, which we can follow up on, for example:
  - `SkTypeface`:
    > Typeface objects are immutable, and so they can be shared between threads.
  - `SkBitmap`:
    > SkBitmap is not thread safe. Each thread must have its own copy of SkBitmap fields,
    although threads may share the underlying pixel array.
- Sometimes it's interesting to take a look at the implementation. For example, `SkTypeface` is not actually immutable, but maintains the illusion by using thread synchronization to compute values lazily.

**Comment by ostera** [comment]
@pragmatrix, fantastic! :tada:

For the sake of unblocking work I have on top of this I can begin by making all types `Send + Sync` on their wrappers, and we can work backwards from there on a PR to tighten things up, and make sure it ends up the safest it we can make it. How does that sound?

PS: I'm going to need some help since bindings _to Rust_ aren't really my forte either :see_no_evil:
