### ISSUE TITLE
Building for aarch64-apple-ios

### ISSUE THREAD

**Issue by triniwiz** [rust-skia/rust-skia#296]
Hi I’m trying to test out that new metal feature (thank you by the way) but building for aarch64 seems to always fail building I think the test app ... 

![D436D3F5-48AA-468D-866A-2FBD151AF9D8](https://user-images.githubusercontent.com/6695919/75188397-71532380-5722-11ea-8d90-5d2746ce21de.jpeg)

After googling a bit I saw someone mentioned setting `is_component_build=true` in `gn` I think it suppose to skip the app building phase that fails 🤣

![29C3B693-6396-4925-BE24-ABAF4F533F59](https://user-images.githubusercontent.com/6695919/75188595-c68f3500-5722-11ea-95d6-fdfae2b4ebdc.jpeg)

I think there might be two other ways to get pass that failing build according to the Skia site 

- If you find yourself missing a Google signing identity or provisioning profile, you'll want to have a read through go/appledev.

- skia_ios_identity=".*Jane Doe.*"
skia_ios_profile="iPad Profile"

Any help would be appreciated thanks 🙂

**Comment by pragmatrix** [comment]
Interesting, I've encountered a similar problem for the first time in the M81 update of Skia, which is now a blocker for #280. You can see that [in the CI logs](https://dev.azure.com/pragmatrix-github/rust-skia/_build/results?buildId=2650&view=logs&jobId=76d16813-8edc-5f4f-0dbe-cc9a2f8c7595&j=76d16813-8edc-5f4f-0dbe-cc9a2f8c7595&t=54b2e321-fbff-5386-8182-7ff018d12c95). 

I don't think that `is_component_build` will help or that signing should be needed to build the static Skia libraries: `is_component_build` seems to reconfigure the build scripts to build dynamic libraries instead of static ones and I don't like the idea to build a test application that is not actually referred to in the output binaries we use.

This looks more like a gn configuration problem that causes skottie's test application to be built on iOS and I've not found a switch to turn that off so far.

I've specifically prepared for that in #293 and #294, so that we can modify BUILD.gn configuration files directly. May be I do have time for that tomorrow. You can try that if you want with the current master, but before that make sure that the `git submodule update` invocation is commented out in `skia-bindings/build_support/skia.rs`.
