### ISSUE TITLE
MacOS Catalina 10.15.3 seg fault in release mode

### ISSUE THREAD

**Issue by Kethku** [rust-skia/rust-skia#299]
After a long investigation it was determined that skia-safe and skia-sys version 0.26.1 causes a segfault in release builds on MacOS Catalina.

Details can be found here: https://github.com/Kethku/neovide/issues/126

Unfortunately I have little in the way of details as I don't personally have a Mac, but the issue seemed to be relatively prevalent for Mac users.

**Comment by pragmatrix** [comment]
Thank you for reporting that. 

After building a number of configurations I do now think that the segfault is caused by a mixup of the harfbuzz functions that the final executable is linked to.

Sadly, I do have only indirect proof, because as it happens, I found no way to analyze exactly how the final executable of novide relates to the static object files.

Observations:

- The segfault can be reproduced even when no skia-safe code is run.
- The current rust-skia master causes the segmentation fault, too (version 0.26.8).
- It does not dependent on the CLang (Apple 11, or 9.0.1) used or if prebuilt binaries are downloaded.
- It does, however, depend on the optimization level: the segfaults do not happen with `opt-level=0`, that's why debug builds run fine.

If the harfbuzz version is updated to 2.6.4 either in master, or in the upcoming M81 update (#280) , the segfault disappears.

The only explanation seems to me that neovide / skribo accidentally uses functions of the older harfbuzz version (1bada656a86e9cb27d4a6b9fcc50748f0bd9c1d9) that comes with the skia-bindings libraries instead of the embedded_harfbuzz library that comes with harfbuzz-sys.

However, this does not explain why 0.23.2 works. The only significant difference compared to 0.26.1 is that the harfbuzz object files were moved from the static skshaper library to the static Skia library because of #248. Depending on the linker order and the behavior of Rust what happens with duplicated functions, there might be a possibility that this move caused Rust to prefer some harfbuzz code from Skia.

I personally would expect that Rust would complain on duplicated C function, but it seems that they just got linked _somehow_. I did some builds with an incomplete harfbuzz library in the Skia build, and the missing functions got pulled from the embedded_harfbuzz library. Scary at least.

What works:

- Modify skribo to not embed harfbuzz alongside with it by disabling the default feature `build-native-harfbuzz` of its harfbuzz-sys and harfbuzz dependencies.
- Use version 0.23.1 (which neovide does now). 
- Use the updated version M81, that contains the same version of harfbuzz like the one compiled in harfbuzz-sys. Though, an update of one of the two harfbuzz code bases may cause a segfault again.

Another, probably safer, option would be to introduce a skia-bindings feature that directly depends on harfbuzz-sys, but I am not sure of the resulting consequences for the prebuilt binaries.

**Comment by Kethku** [comment]
Wow thanks for the super indepth analysis. This explains a lot

I think on the neovide side I'm going to use 0.23.1 and then update to M81 once that is available as 0.23.1 seems to be working for me.

On the why this happens side, I wonder if this should be brought up with the Rust team. Either this is something non standard which should be addressed, or documentation should be such that the chance of this happening should be more obvious. Either way, this was a non-obvious issue that was very hard to track down. That said, I'm not sure about the preferred way to bring something like this up with the team without being demanding etc...

Thanks again for the details!
