### ISSUE TITLE
`&mut` self in the API

### ISSUE THREAD

**Issue by therealbnut** [rust-skia/rust-skia#300]
Hey, many methods seem to be marked as `&mut self`, like in `paragraph.rs`:

https://github.com/rust-skia/rust-skia/blob/448537d9967b693fe09a0f8c2ad156176cc75bad/skia-safe/src/modules/paragraph/paragraph.rs#L98

It doesn't seem like these getter methods requires mutability, unless there's some kind of memoization. How are we deciding what should be mutable? Is it based on `const` annotations on methods in the C++?

It'd be nice to make sure we have correct mutability so that this doesn't leak into our rust code, what's the best way for me to help us improve this?

**Comment by pragmatrix** [comment]
Correct, the original C++ functions don't mark the methods `const`. I truly wondered when I was generating the wrappers, because even if memoization would be used, such functions would be observable as being `const`.

And I've just read the following comment:
```
 Experimental API that allows fast way to update "immutable" paragraph
```
above some virtual functions in the `Paragraph` class, which were removed in the current master. So, at least `Paragraph` is meant to be immutable.

If you'd like to create a PR, I'm fine with changing that on the Rust side, which should not introduce any incompatibilities but may require some nasty const_casts. Of course, you could post this into the Skia bugtracker, too, but that would probably take some months until it lands here.

Also note that the textlayout Skia classes are a fairly new API, and I see breaking changes in every Milestone update, so the Skia team might probably adjust the signatures in the future, too.

**Comment by therealbnut** [comment]
Thanks for the insight. When I get time I’ll approach it from upstream Skia and Rust here.
