### ISSUE TITLE
Fresh Windows Build Fails with `can't open file 'skia/tools/git-sync-deps'`

### ISSUE THREAD

**Issue by pragmatrix** [rust-skia/rust-skia#31]
With:

`python: can't open file 'skia/tools/git-sync-deps': [Errno 2] No such file or directory`

This is probably because of this https://github.com/rust-skia/rust-skia/blob/master/skia-bindings/build.rs#L13

@Brooooooklyn What was the intention behind that? I've seen that the skia clone is done in the azure script, shouldn't it be done in `build.rs` like on the other platforms?

**Comment by pragmatrix** [comment]
https://github.com/rust-skia/rust-skia/commit/6531c2f186cd9ec8f15c7a28d61118b25c2973e5

**Comment by Brooooooklyn** [comment]
When I was initializing the `azure pipeline`, I noticed that a `error: timer thread did not terminate timely` displaying  in Windows console.
I thought it was caused by the `git clone skia via build.rs`.
But now I think I was mistake, maybe you should add the `git submodule update skia` logic back in `build.rs`
