### ISSUE TITLE
Cannot convert Surface/Canvas Object between C/Rust

### ISSUE THREAD

**Issue by colorhook** [rust-skia/rust-skia#310]
While using ffi feature, invoke from C to Rust, or from Rust to C.

I can't convert  Surface/Canvas struct instance in Rust to pointer in C, because all related methods are privated, such as `Canvas::borrow_from_native`, `Canvas::own_from_native_ptr`, `RCHandle::native_mut`, and `RCHandle::from_ptr`.

Can you give some tips?

**Comment by pragmatrix** [comment]
Hi, all wrapper types should be marked with `repr(transparent)`. so I guess it is currently somehow _safe_ to cast them with `std::mem::transmute`.

I will, however, make these conversion functions public, so that usecases like yours are supported.

**Comment by pragmatrix** [comment]
I've prepared an initial PR that exports some additional unsafe traits on top of the wrappers. Please take a look to see if that would cover your needs: #320.

A wrapper trait for the `Borrow` type is missing so far, because I don't know how that could be useful, may be you could provide an example?
