### ISSUE TITLE
`path_2d_path_effect` returns a PathEffect rather than an Option

### ISSUE THREAD

**Issue by samizdatco** [rust-skia/rust-skia#360]
As far as I can tell, all but one of the PathEffect `new` functions return an `Option<PathEffect>` rather than handing off the object directly: 
https://github.com/rust-skia/rust-skia/blob/d5fdcc98b99952d47f45f8351d3189f0cc26309b/skia-safe/src/effects/_2d_path_effect.rs#L20
https://github.com/rust-skia/rust-skia/blob/d5fdcc98b99952d47f45f8351d3189f0cc26309b/skia-safe/src/effects/_1d_path_effect.rs#L28
https://github.com/rust-skia/rust-skia/blob/d5fdcc98b99952d47f45f8351d3189f0cc26309b/skia-safe/src/effects/dash_path_effect.rs#L12
https://github.com/rust-skia/rust-skia/blob/d5fdcc98b99952d47f45f8351d3189f0cc26309b/skia-safe/src/effects/corner_path_effect.rs#L12
https://github.com/rust-skia/rust-skia/blob/d5fdcc98b99952d47f45f8351d3189f0cc26309b/skia-safe/src/effects/discrete_path_effect.rs#L16-L20

The one exception seems to be `path_2d_path_effect`:
https://github.com/rust-skia/rust-skia/blob/d5fdcc98b99952d47f45f8351d3189f0cc26309b/skia-safe/src/effects/_2d_path_effect.rs#L30

Is this just an oversight or is there a reason for the inconsistency?

**Comment by pragmatrix** [comment]
> Is this just an oversight or is there a reason for the inconsistency?

So far I got accustomed to checking the Skia documentation first, and if it's ambiguous, I'll take a look at the implementation if a `nullptr` may be returned based on invalid input. In the case of 2d path effect, a `nullptr` can never be returned:

```c++
    static sk_sp<SkPathEffect> Make(const SkMatrix& matrix, const SkPath& path) {
        return sk_sp<SkPathEffect>(new SkPath2DPathEffect(matrix, path));
    }
```
If there would be any doubt, I'd would usually prefer to return an Option. Compare this to:

```c++
sk_sp<SkPathEffect> SkDiscretePathEffect::Make(SkScalar segLength, SkScalar deviation,
                                               uint32_t seedAssist) {
    if (!SkScalarIsFinite(segLength) || !SkScalarIsFinite(deviation)) {
        return nullptr;
    }
    if (segLength <= SK_ScalarNearlyZero) {
        return nullptr;
    }
    return sk_sp<SkPathEffect>(new SkDiscretePathEffect(segLength, deviation, seedAssist));
}
```

It stands to reason that implementation changes cannot be foreseen and in the future there may be a situation in which `_2d_path_effect::new()` panics because of invalid input, but usually this is exactly what you would want for such an exceptional case and the calling site probably would do that anyways if an Option is returned. 

So in general, when a C++ smart pointer is returned, I've started to decide to use an Option on a case to case basis, because otherwise some of the APIs would be very cumbersome to use.

**Comment by pragmatrix** [comment]
Closing this in the hope that my explanation answers the question and provides a good enough reason for keeping the API inconsistent. Please reopen, if you think otherwise.
