### ISSUE TITLE
Image is scaled differently depending on filter quality

### ISSUE THREAD

**Issue by romanzes** [rust-skia/rust-skia#371]
I'm using the following code to draw an `SkImage` on `SkCanvas`:
```rust
        let mut paint = Paint::default();
        paint.set_anti_alias(true);
        paint.set_filter_quality(FilterQuality::High);
        canvas.draw_image_rect(&image, None, dest_rect, &paint);
```

Here is an example of an image rendered with `FilterQuality::High`:
![raster output](https://user-images.githubusercontent.com/5735967/89619376-35c3a480-d8d1-11ea-873c-41627a7bba2d.png)

`FilterQuality::Low`:
![raster output](https://user-images.githubusercontent.com/5735967/89619527-70c5d800-d8d1-11ea-9f04-d2ec7c15c849.png)

It seems that when the image is rendered with high quality, a line of subpixel breadth is eaten from each of the edges, resulting in a slightly different scale. I made a gif so it's easier to notice:
![output](https://user-images.githubusercontent.com/5735967/89620592-3a895800-d8d3-11ea-944f-cd47df4c1840.gif)

**Comment by pragmatrix** [comment]
It seems that the high quality image is slightly zoomed, which is probably related to the filter algorithm that - I assume - needs to reduce the source image's rectangle slightly so that the filtering takes only pixels into account that are inside, otherwise the interpolation of the border pixels would have to access pixels outside the image, leading to artifacts.

Maybe also enabling anti-aliasing has an effect?

I took a look at the wrapper functions in skia-safe, and see no hint that they could be interfering. To continue, you can either tweak the source rectangle, open an issue at Skia's bugtracker: https://bugs.chromium.org/p/skia/issues/list or the forum https://groups.google.com/forum/#!forum/skia-discuss
