### ISSUE TITLE
Could image_filters::image accept an &Image?

### ISSUE THREAD

**Issue by samizdatco** [rust-skia/rust-skia#377]
The `image_filters::image` filter applies positioning/cropping/scaling to an `Image` in a manner similar to `canvas::draw_image_rect`. I presume a main use-case for this is to allow these transformations to be 'burned into' and image so it can then be simply drawn to a point via `canvas::draw_image`. 

For example:

```rust
let src:Rect = ...; // crop original
let dst:Rect = ...; // set position & scale
let quality:FilterQuality = ...;

let image:Image = ...;
let bounds = image.bounds();
if let Some(filter) = image_filters::image(image.clone(), Some(src), Some(dst), quality){
  if let Some((new_image, new_bounds, new_origin)) = image.new_with_filter(&filter, bounds, bounds){
    // draw the resulting image at new_origin
  }
}
```

At the moment this requires making an interim clone of the original image to pass to `image_filters::image` since it doesn't accept a reference for its image argument:
https://github.com/rust-skia/rust-skia/blob/fdf06cfd6739ee7027be7520b0f4941cfdeb4bd9/skia-safe/src/effects/image_filters.rs#L152-L157

Is there any way this could change, or does the underlying method actually require taking ownership of the original `Image`?

**Comment by pragmatrix** [comment]
This is one is also one of the choices I made after being confused about why the Skia API uses different signatures when passing a reference counted "object". Whenever the Skia API takes in a smart pointer (in this case `sk_sp<SkImage>`), I assumed that an ownership transfer was intended, because the alternative would be passing a mutable reference to an SkImage - which does not make sense at all. So for these cases, I've propagated the ownership transfer to the caller (Rust), which - at first - seems counter-intuitive and non-idiomatic, but if you consider that "cloning" a reference counted Skia object is just a cheap increase of a reference count it starts making sense again.

To reduce that confusion, I am open to suggestions. One idea that I just had, is to use something in the veins of the `ToOwned` trait making it possible to either pass a reference or move the object.

**Comment by pragmatrix** [comment]
I am not sure about this, but it seems that the situation when an owned value is preferred over a reference is quite unusual in Rust making the use of `ToOwned` and `Cow` traits hardly applicable. 

But I've had some success with the following trait:

```rust

pub trait AsOwned<OwnedT> {
    fn as_owned(self) -> OwnedT;
}

// identity
impl<T: NativeRefCountedBase> AsOwned<RCHandle<T>> for RCHandle<T> {
    fn as_owned(self) -> Self {
        self
    }
}

// from reference
impl<T: NativeRefCountedBase> AsOwned<RCHandle<T>> for &RCHandle<T> {
    fn as_owned(self) -> RCHandle<T> {
        self.clone()
    }
}
```

It would be a bit of work to change all the wrapper functions that expect a transfer of ownership of reference counted Skia objects, but I think it might be worthwhile and would most probably not introduce a breaking change. What do you think?

**Comment by pragmatrix** [comment]
Well, it's much simpler as that, there is already a `From<&RCHandle<T>> for RCHandle<T>` which can be utilized by using `impl Into<>` in the argument position of every function that wants to own a reference counted Skia object. #379
