### ISSUE TITLE
Which image formats are supported on which platforms?

### ISSUE THREAD

**Issue by samizdatco** [rust-skia/rust-skia#389]
I was surprised to discover that (at least on macOS) skia-safe doesn't seem to be able to encode images in quite a few of the formats listed in the `EncodedImageFormat` enum. So far, `JPEG` and `PNG` seem to be the only values that will produce any output from `Image::encode_to_data`:
- [ ] `BMP`
- [ ] `GIF`
- [ ] `ICO`
- [x] `JPEG`
- [x] `PNG`
- [ ] `WBMP`
- [ ] `WEBP`
- [ ] `PKM`
- [ ] `KTX`
- [ ] `ASTC`
- [ ] `DNG`
- [ ] `HEIF`

Would adding support for (some of) these other formats be something that could happen as part of the skia-bindings build process or is the issue more that Skia itself only supports these formats on a platform-by-platform basis?

**Comment by pragmatrix** [comment]
I think I've accidentally removed `gif` support when I was trimming the dependencies in #293. `gif` seems to be the only format for which the build.gn script decides to add it based on a file test, which is cruel at least. Most of the other formats need to be enabled by a gn argument, and `dng` got disabled it because of compile errors. For `bmp` and `ico`, I assume that they are Windows only.

What I can imagine is that we add standard / basic formats and all the ones which are cheap to include (i.e. compile properly and are small), and add one more feature that includes all the remaining formats we are able to add.

And at the very least this requires clarification. I'll dive in deeper as soon I find time for it.

**Comment by pragmatrix** [comment]
Update:

By default, only the formats JPEG and PNG can be encoded. Decoding of BMP, GIF, ICO, JPEG, PNG, and WBMP is enabled on all platforms in the upcoming skia-safe version 0.34.1 (skia-safe versions < 0.34.1 are not supporting GIF). WEBP docoding _and encoding_ must be enabled explicitly, for which I'll try to introduce an additional feature in #390. The formats PKM, KTX, ASTC don't seem to be supported at all (from scanning the Skia source, they seem to be related to texture compression formats which are used on the GPU only). DNG and HEIF may be enabled through features in the future if users of skia-safe show interest in them.
