### ISSUE TITLE
Support WebAssembly

### ISSUE THREAD

**Issue by pragmatrix** [rust-skia/rust-skia#39]
Followup from https://github.com/rust-skia/rust-skia/issues/24#issuecomment-471984934 

We ~~need~~ want to support WebAssembly.

**Comment by pragmatrix** [comment]
Note that there is a version of a Skia's Canvas API available as an WASM npm package:

https://www.npmjs.com/package/canvaskit-wasm
https://skia.org/user/modules/canvaskit

/cc @Brooooooklyn @M-Adoo

**Comment by Brooooooklyn** [comment]
Oh it's cool, seems like we don't need support wasm in our approach

**Comment by M-Adoo** [comment]
canvas-kit  has different api. So, if user  use this lib, can not just compile his rust code to wasm.

**Comment by jbowens** [comment]
I'd be really interested in WebAssembly support!

I don't have very much context on the state of the world of rust, wasm-pack and wasm-bindgen. I did come across [this quote in the Rust WASM Book](https://rustwasm.github.io/docs/book/reference/which-crates-work-with-wasm.html#c-and-system-library-dependencies):

> ### Things a Crate Might do that Won't Work with WebAssembly
> #### C and System Library Dependencies
> There are no system libraries in wasm, so any crate that tries to bind to a system library won't work.
>
> Using C libraries will also probably fail to work, since wasm doesn't have a stable ABI for cross-language communication, and cross-language linking for wasm is very finicky. Everyone wants this to work eventually, especially since clang is shipping their wasm32 target by default now, but the story isn't quite there yet.

It might be possible with the [wasm32-unknown-emscripten](https://www.hellorust.com/setup/emscripten/) target?

Another option is to try to adapt Skia's CanvasKit emscripten build process to produce a wasm module with the original API, and then [wrap the wasm module w/ a Rust interface using wasm-bindgen](https://github.com/rustwasm/wasm-bindgen/issues/1202). It does seem preferable to build a single wasm module, so you don't need to bounce back and forth between the application wasm module, js, and the Skia wasm module.

**Comment by blockspacer** [comment]
if anyone interested in SKIA based GUI in browser - that project can be useful blockspacer/skia-opengl-emscripten#2 , ported some parts of chromium ui to WASM with and without threads support.

**Comment by aclysma** [comment]
Hey just wanted to say, this sounds pretty interesting. I have a project that implements basic Skia drawing in a window (https://github.com/aclysma/skulpin) with the goal of making simple 2D apps easy and accessible. Today I got to thinking what it might look like to expose the Skia canvas via wasm. Maybe to support hot-reload of drawing code or for hosting other languages.

Also thanks so much for the work on this crate. I'm super impressed with the quality of the bindings and the distribution method that avoids downstream users from having to build Skia itself is extremely helpful!

**Comment by pragmatrix** [comment]
@aclysma Thanks for putting some trust in this project. Skulpin really looks like a decent start for a Vulkan based Rust user interface library.

Regarding WASM, I've just added a PR (#221) that contains my latest build experiments on Ubuntu. So far, it  builds Skia, skia-bindings, the bindings.rs file, and also skia-safe, but linking a small example fails. I'll try to find some more time to follow up, but also like to invite everyone interested to step in.

**Comment by markfarnan** [comment]
Any updates to this ?

I'm trying to find a good 2D graphics library I can use with WASM onto HTML5 Canvas natively from Rust and SKIA seems to be good if the WASM compile works ?

**Comment by Ziriax** [comment]
We have Skia wasm working in the browser, C++ only, with emscripten SDL2. Would it help if I provide that code?

**Comment by EisenbergEffect** [comment]
I'd be interested to see repo with that setup for sure.

**Comment by Ziriax** [comment]
It seems the Skia updates from the last weeks broke my demo... It still links, but crashes with a `RuntimeError: invalid index into function table`. I noticed some Skia commits related to `fixed build warnings with emsdk 2.0`, so I'm going to try with the newer version...

**Comment by Ziriax** [comment]
Got it working again.

See https://github.com/Ziriax/SkiaWasmDemo

It's just an experiment. Currently uses Skia/m86 and EMSDK 2.0.4

It uses Docker, so should run everywhere, but I only made batch files for Windows.

Have fun!

**Comment by tuxmark5** [comment]
I've been successfully using rust-skia with WebAssembly for months now. I managed to port it to wasm32-unknown-emscripten at first, and then later to wasm32-unknown-unknown (by using a custom wrapper for clang executable that invokes emscripten's emcc and em++ instead of the usual clang as well as some patches to emsdk).

Both require one of the newer versions of rust-bindgen (i'm using commit e0961491034b243cc23c40619da732cd5680f4c6), which contains the patch I submitted to fix linker errors regarding C++ constructor return types (anything past 4608a11b5cbdcc779bd78c0e14735864a95ed893 should work).

Here's the fork:
https://github.com/tuxmark5/rust-skia

Using it with wasm32-unknown-unknown is slightly trickier, as you have to supply your own JavaScript runtime that provides OpenGL functions that are used by WebGL backend of skia, as well as to export malloc/free (which simply use Rust's global allocator) and a few pthreads functions (completely empty functions that just return 0). Furthermore I had to completely disable emscripten's longjmp support by patching/commenting out a few lines in some of the python scripts. Finally I had to remove memset and a few other functions from emscripten's runtime as those are provided by Rust already and would cause linker conflicts.

**Comment by JackRedstonia** [comment]
@tuxmark5 I think you should open a PR merging your fork.

**Comment by Brooooooklyn** [comment]
Since https://github.com/Brooooooklyn/canvas provide the excatly same API with HTML canvas, it could be compied into wasm using `wasm-bindgen` easily, I will try it in next few months.

Ref: https://github.com/Brooooooklyn/canvas/issues/313

**Comment by flupke** [comment]
I have been working on a patch, adapted from @tuxmark5 work: https://github.com/jitter-video/rust-skia/tree/wasm

It only supports the `wasm32-unknown-unknown` target because there is a fundamental incompatibility between the `wasm32-unknown-unknown` target and linking with C: https://github.com/rustwasm/team/issues/291#issuecomment-645482430

I will contribute a PR soon (I want to add an example).
