### ISSUE TITLE
How to use `metal` backend?

### ISSUE THREAD

**Issue by songww** [rust-skia/rust-skia#413]
I have got `segmentation fault`

code:
```rs
    use metal;
    let device = metal::Device::system_default().expect("no metal device found");
    let descriptor = metal::TextureDescriptor::new();
    descriptor.set_pixel_format(metal::MTLPixelFormat::RGBA8Unorm_sRGB);
    let texture = device.new_texture(&descriptor);
    let mut gr_context =  {
        let boxed_device = Box::new(device);
        let boxed_queue = Box::new(queue);
        let device_ptr = Box::into_raw(boxed_device) as *mut ffi::c_void;
        let queue_ptr = Box::into_raw(boxed_queue) as *mut ffi::c_void;
        skia::gpu::Context::new_metal(device_ptr , queue_ptr).expect("can not create metal context.")
    }
    let texture_info = unsafe {
        let boxed = Box::new(texture);
        let texture_ptr = Box::into_raw(boxed) as *const ffi::c_void;
        skia::gpu::mtl::TextureInfo::new(texture_ptr)
    };
    let suface_props = skia::SurfaceProps::default();
    let backend_render_target = skia::gpu::BackendRenderTarget::new_metal((width as i32, height as i32), 1, &texture_info);
    let surface = skia::Surface::from_backend_render_target(&mut gr_context, &backend_render_target, skia::gpu::SurfaceOrigin::TopLeft, skia::ColorType::RGBAF16Norm, None, Some(&suface_props)).unwrap();
```
thanks.

**Comment by ctrlcctrlv** [comment]
This may not help, but I find the best way to use Skia's Metal GPU backend is through Skulpin. That's what I do in [Qglif](https://github.com/mfeq/Qglif). It uses Vulkan, yes, but that's better for most people since it's cross-platform, and it technically _is_ Metal since MoltenVK converts Vulkan into Metal.

**Comment by pragmatrix** [comment]
@songww If you are using [metal_rs](https://crates.io/crates/metal-rs), the metal resource pointers of the need to be converted with `.as_ptr() as *mut ffi::c_void`. Boxing them and using `into_raw()` will produce a pointer to a pointer. You should probably also take a look at the skia-org project for a [working metal surface setup](https://github.com/rust-skia/rust-skia/blob/master/skia-org/src/drivers/metal.rs). 

If that does not help, please post a full repro.

**Comment by pragmatrix** [comment]
Closing because of no feedback, but I am wondering if skia-safe should by default use [metal-rs](https://crates.io/crates/metal) to make interfacing with Metal easier and safer. For D3D, I've decided to use the [winapi wrappers](https://crates.io/crates/winapi), but also found that there [are](https://github.com/gfx-rs/d3d12-rs) [others](https://docs.rs/dxplr/0.0.23/dxplr/), which should probably be supported. I guess that in the long run this project may require additional crates to interface with specific backend wrappers.
