### ISSUE TITLE
Please impl Debug for Handle

### ISSUE THREAD

**Issue by ctrlcctrlv** [rust-skia/rust-skia#514]
Even if it will just always output something like `Handle<SkPath>`, it would be a big help so I could impl Debug on structs which include Skia primitives.

**Comment by pragmatrix** [comment]
Sounds reasonable. I've just put a `#derive(Debug)` on Handle, but it looks like this would do a bit too much:

For an empty bitmap `{:?}` output would be:
```
Handle(SkBitmap { fPixelRef: sk_sp { fPtr: 0x0, _phantom_0: PhantomData }, fPixmap: SkPixmap { fPixels: 0x0, fRowBytes: 0, fInfo: SkImageInfo { fColorInfo: SkColorInfo { fColorSpace: sk_sp { fPtr: 0x0, _phantom_0: PhantomData }, fColorType: kUnknown_SkColorType, fAlphaType: Unknown }, fDimensions: SkISize { fWidth: 0, fHeight: 0 } } }, fMips: sk_sp { fPtr: 0x0, _phantom_0: PhantomData } }, PhantomData)
```

Is this too much, or is the general expectation to see deep into The Matrix with `Debug`?

As an alternative, we could implement `Debug` and simply print the wrapped type with [`std::any:type_name`](https://doc.rust-lang.org/std/any/fn.type_name.html) as suggested. This would also be more consistent, because some of the Skia types are opaque blobs and their default `Debug` implementation would just output binary nonsense.

**Comment by ctrlcctrlv** [comment]
Obviously I'd be happy to get _any_ output just so I can have `Debug` on my structs which include Skia types (I have a lot of those), but for me, the best would be 9 times out of 10 just the name of the type. I think that for some types like `SkPath`, dumping the points would be OK. But in most cases, like `SkBitmap`, just the word `SkBitmap` would make me happy.

It's up to you though :)

**Comment by pragmatrix** [comment]
I hope I was not going over the top by implementing `fmt::Debug` by hand for most types. Anyways, now there should be enough Debug information available.

And thank you for bringing this up, this way I began to realize that Debug information is very useful in another project I am working at.

**Comment by ctrlcctrlv** [comment]
Thanks for doing all that work @pragmatrix! It's surely very useful for MFEK project :-) basically all our modules are using Skia in some way.
