### ISSUE TITLE
Add bindings for SkSVGDOM

### ISSUE THREAD

**Issue by samizdatco** [rust-skia/rust-skia#545]
Would it be possible to add bindings for the [`SkSVGDOM`](https://github.com/google/skia/blob/main/modules/svg/include/SkSVGDOM.h) class? Being able to parse SVG files and draw them to the canvas would be a terrific enhancement. 

See also: [SvgTool.cpp](https://github.com/google/skia/blob/main/modules/svg/utils/SvgTool.cpp) for a minimal use case.

**Comment by pragmatrix** [comment]
> Being able to parse SVG files and draw them to the canvas would be a terrific enhancement.

Agreed, and as I can see from the Network graph, @triniwiz already attempted to extend the bindings, may be you can collaborate?

**Comment by pragmatrix** [comment]
@triniwiz Is it possible to draw SVG files with that branch? We don't have to implement the full SkSVGDOM API (Node, etc.) for a first MVP, rendering should cover most use cases I guess.

**Comment by triniwiz** [comment]
Yes it works fine for my usage passing a string or path from Android/iOS to render . One more thing I know some are a bit picky with it comes to adding dependencies since I added reqwest. It was added from my understanding that embedders need to handle those asset loading e.g images , fonts(did not tackle this one) ..etc

**Comment by pragmatrix** [comment]
Bindings for SkSVGDom are available for a long time now, closing, see #681.
