### ISSUE TITLE
segfaults

### ISSUE THREAD

**Issue by iitalics** [rust-skia/rust-skia#669]
im trying out skia-safe 0.53 for the first time, and i get segmentation fault for the following code:

```rs
use skia_safe as sk;

fn main() {
    let info = sk::ImageInfo::new(
        (400, 400),
        sk::ColorType::BGRA8888,
        sk::AlphaType::Premul,
        sk::ColorSpace::new_srgb(),
    );
    let mut bitmap = sk::Bitmap::new();
    if !bitmap.set_info(&info, None) {
        panic!("set_info failed");
    }

    let mut canvas = sk::Canvas::from_bitmap(&bitmap, None);
    canvas.clear(0x999900);
}
```

**Comment by pragmatrix** [comment]
Thank you a lot for the report.

I can reproduce this on Windows, and it looks to be "by design" in terms of the Skia C++ API that `set_info()` does not allocate the pixels and leaves the `Bitmap` in a state that crashes when drawing to a `Canvas`.

To make this work, pixels need to be allocated, so add

```rust
    if !bitmap.try_alloc_pixels() {
        panic!("allocation of pixels failed");
    }
```
after the `set_info` invocation to make this work.

I'll keep this issue open until we figure out how to make this combination of API calls safe and what are the circumstances are that a `Canvas` can draw to a `Bitmap` without pixels.

**Comment by pragmatrix** [comment]
Created an issue in the Skia bugtracker: https://bugs.chromium.org/p/skia/issues/detail?id=13634

**Comment by pragmatrix** [comment]
The Skia developers confirmed that the segfault is expected, therefore I've decided to change the return type in `Canvas::from_bitmap` and return `None` if the bitmap can not be drawn to in #671.
