### ISSUE TITLE
WASM build fails to obtain document RCHandle

### ISSUE THREAD

**Issue by igrekun** [rust-skia/rust-skia#694]
[This line](https://github.com/rust-skia/rust-skia/blob/ce61f7808b72e8bf6b2c0e201aa7fab6ee927f7e/skia-safe/src/docs/pdf_document.rs#L260) in pdf_document.rs panics trying to unwrap None value on wasm emscripten target.

Are there certain keys related to PDF that are disabled in build configuration?

**Comment by pragmatrix** [comment]
This is very unexpected. All code I've read so far makes this effectively impossible that the Document creation returns a `nullptr` as long the stream creation did not fail. 

Can you post the trace and / or try with the full source compiled with `SKIA_DEBUG=1`?

**Comment by igrekun** [comment]
Sure, this is the sample code
```
use skia_safe::{Data, Color};

fn main() {}

#[no_mangle]
pub fn test_pdf() {
  let doc = skia_safe::pdf::new_document(None);
  let mut page = doc.begin_page((16., 16.), None);

  let canvas = page.canvas();
  let mut paint = skia_safe::Paint::default();
  paint.set_stroke(false);
  paint.set_color(Color::from_rgb(8, 8, 8));
  canvas.draw_rect(skia_safe::Rect::from_xywh(2., 2., 4., 4.), &paint);
  
  let doc = page.end_page();
  let data = doc.close();
  println!("{:?}", data.as_bytes());
}
```

**Comment by pragmatrix** [comment]
Can reproduce, and I've found the problem, Skia disables PDF support in WASM builds and compiles another file `SkDocument_PDF_None.cpp` that return a `nullptr`. Interestingly, overriding this GN check for WASM makes PDF document support compile successfully. So I'll try to force-enable this until someone shows that PDF support is otherwise broken. May be the reason for disabling PDF support does not hold anymore or they just removed PDF support for other reasons like reducing the size of the WASM binaries.
