### ISSUE TITLE
gpu::SurfaceOrigin::BottomLeft / TopLeft inverted

### ISSUE THREAD

**Issue by pekim** [rust-skia/rust-skia#84]
It appears that the values of `skia_safe::gpu::SurfaceOrigin::BottomLeft` and `skia_safe::gpu::SurfaceOrigin::TopLeft` are the wrong way round.

I want TopLeft and was puzzled about the positions of what I drew on a canvas. On a whim I tried BottomLeft, and the origin behaves as though it is TopLeft.

I'm depending on commit 38396d0.

(Awesome project by the way.)

**Comment by pragmatrix** [comment]
> (Awesome project by the way.)

Thank you!

The bindings [seem to be correct](https://github.com/rust-skia/rust-skia/blob/38396d0604a25106d3244883e43df468f52bc90f/skia-safe/src/gpu/types.rs#L28) and I've also verified that the values are converted and passed around correctly in the various functions that use `gpu::SurfaceOrigin`. Can you provide a repro?

**Comment by pragmatrix** [comment]
I've tried to reproduce that with a [skia surface as an vulkan image / texture](https://github.com/pragmatrix/skia-voodoo) with both the master and m74 branch of rust-skia. 

Behaving as expected, (0,0) on the canvas renders at the surface's origin. May be it's different with OpenGL, where the texture origin is at the bottom left.

**Comment by pekim** [comment]
I probably won't have time to create a minimal reproduction today. But I should be able to do so tomorrow, as it's a public holiday in the UK.

**Comment by pekim** [comment]
https://gist.github.com/pekim/b31094013654708829c9ad749f927c35
The blue square appears at the bottom left.
Changing the surface origin to BottomLeft, the square appears at the top left.

In order to keep the reproduction minimal, there is no attempt to create a new render target on window resize. So resizing the window may cause the square to move within the window. That's fine.

**Comment by pragmatrix** [comment]
Thank you for the repo. I compiled it and inserted some `dbg!` to be sure that `gpu::SurfaceOrigin` were not touched on the binding's side.

And I think now that it actually makes sense. Because there is no easy way for Skia to map GPU coordinates to Canvas coordinates, that information has to be provided.

For OpenGL, the origin is at the bottom left (your repro) and in Vulkan _the default_ is top left, but in Vulkan there [is also an extension that can flip a framebuffer's y axis](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VK_KHR_maintenance1). So when  `gpu::SurfaceOrigin` is interpreted as the origin of the GPU buffer, it is correct. TopLeft for Vulkan backends, BottomLeft for OpenGL backends.

If - like in our [skia-org OpenGL backend](https://github.com/rust-skia/rust-skia/blob/master/skia-safe/examples/skia-org/main.rs#L108) - only functions that are accessing Canvas are used, `gpu::SurfaceOrigin` can be changed without an observable effect. It's like painting and looking through a lense but never seeing the original picture. In contrast to that, when the backing GPU buffer is accessed, it's important to Skia to know how this lense must look like to properly map the Canvas's coordinate system to the screen.

**Comment by pekim** [comment]
I've looked out some code I have where I toyed with glfw and skia in Go. And I see that I had used BottomLeft to achieve a top left origin. So it appears that I've had this problem before, and my memory failed me.

I apologise for wasting your time. I'll close this issue.
