### ISSUE TITLE
Affected by CVE-2023-5129?

### ISSUE THREAD

**Issue by marc2332** [rust-skia/rust-skia#841]
I think skia-safe might affected by CVE-2023-5129, right? It seems to be an exploit with webp (which is behind a feature anyway)

I think skia has already fixed the dependency itself, so just pulling the latest changes would fix it 

Skia commit: https://github.com/google/skia/commit/1176deb1ac552f05092be69fc30b49245bb9f897
SkiaSharp (just related): https://github.com/mono/SkiaSharp/issues/2608

The patch is newer than https://github.com/rust-skia/rust-skia/pull/834 btw

**Comment by pragmatrix** [comment]
Thank you Marc. 

According to [CVE-2023-5129](https://nvd.nist.gov/vuln/detail/CVE-2023-5129), the CVE got rejected, and instead  [CVE-2023-4863](https://nvd.nist.gov/vuln/detail/CVE-2023-4863) got updated and states that there is a "Heap buffer overflow in libwebp in Google Chrome prior to 116.0.5845.187". But I don't see patches in neither m116, nor m117, and - as you noted - also not in the m118 Skia branch.

Anyways, I will prepare a patch release 0.66.3, update master which is on m117 and update #834, too.

I am not sure if we should post to the advisory-db because specific features can't be marked, and there is a [precedent](https://github.com/rustsec/advisory-db/issues/1755) advising against for a case of an unsoundness issue.

**Comment by pragmatrix** [comment]
Released in [version 0.66.3](https://github.com/rust-skia/rust-skia/releases/tag/0.66.3), closing.

**Comment by marc2332** [comment]
Nice! Good work :sparkles: 

> I am not sure if we should post to the advisory-db because specific features can't be marked, and there is a https://github.com/rustsec/advisory-db/issues/1755 advising against for a case of an unsoundness issue.

Not sure me either, I am not used to this situation :thinking:
